

alpha_vantage_key: "YOUR_API_KEY"
symbols:
  - "AAPL"
  - "MSFT"
  - "GOOGL"
  - "AMZN"
  - "FB"

# Model parameters
n_models: 10
batch_size: 64
base_epochs: 100
meta_epochs: 50
learning_rate: 0.0001

# Trading parameters
initial_balance: 10000
threshold: 0.05

# Training parameters
early_stopping_patience: 10
checkpoint_dir: "checkpoints"
results_dir: "results"
