alpha_vantage_key: "YOUR_API_KEY"

monitoring:
  update_interval: 60
  thresholds:
    price_change: 0.02
    volume_spike: 2.0
    volatility: 0.015
    momentum: 0.05
  alert_handlers:
    - log
    - slack
    - email
  symbols:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN

model:
  train: true
  n_models: 10
  device: "cuda"
  batch_size: 64
  epochs: 100
  symbols:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN
  save_path: "checkpoints/model.pt"
  load_path: "checkpoints/model.pt"

evaluation:
  enabled: true
  initial_balance: 10000
